apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkT0FBOTNtb3okQjRpMlAvSWw2M0V2aEZReVd2OXpILwo=
kind: Secret
metadata:
  creationTimestamp: 2019-05-19T11:00:58Z
  name: mycreds
  namespace: default
type: Opaque

