kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: new-joiner
   namespace: default
rules:
- apiGroups: ["","apps","autoscaling","extensions"] # Core API AND apps
  resources: ["*"]  # pods, services, deployments...
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner-role-binding
  namespace: default
subjects:
- kind: User
  name: oshi
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
